import { describe, expect, it } from 'vitest';
import { addAccount, addDebt, addPayment, addGoal, allocateGoal, createEmptyState, restoreFinanceState, debtRemaining, accountBalance, repayDebt } from './finance';
import * as daily from './daily';
import * as undo from './undo';

function base(){return addAccount(createEmptyState(),{name:'Готівка',type:'cash',initialBalance:100000,lastFour:'',color:'navy'});}
const rule=(s:ReturnType<typeof base>)=>({name:'Інтернет',amount:10000,accountId:s.accounts[0].id,category:'expense-0',frequency:'monthly' as const,startDate:'2028-01-31',nextDate:'2028-01-31',paused:false});
describe('daily tools',()=>{
 it('normalizes legacy state without changing balances',()=>{const s=base();delete s.assistance; const n=restoreFinanceState(s);expect(n.assistance).toEqual({templates:[],recurring:[],nextIncomeDate:''});expect(accountBalance(n,s.accounts[0].id)).toBe(100000);});
 it('keeps templates private and does not spend when creating one',()=>{const s=base(),n=daily.saveTemplate(s,{name:'Кава',kind:'expense',accountId:s.accounts[0].id,category:'expense-0',amount:0,note:'Кава'});expect(n.assistance!.templates).toHaveLength(1);expect(s.assistance!.templates).toHaveLength(0);expect(n.transactions).toHaveLength(0);expect(daily.templateTransaction(n,n.assistance!.templates[0].id).paymentMethod).toBe('cash');});
 it('retains the monthly anchor through leap February',()=>{const s=base(),r=rule(s);expect(daily.nextRecurringDate(r)).toBe('2028-02-29');expect(daily.nextRecurringDate({...r,nextDate:'2028-02-29'})).toBe('2028-03-31');});
 it('retains February 29 for yearly recurrence after a non-leap year',()=>{const r={...rule(base()),frequency:'yearly' as const,startDate:'2028-02-29',nextDate:'2028-02-29'};expect(daily.nextRecurringDate(r)).toBe('2029-02-28');expect(daily.nextRecurringDate({...r,nextDate:'2031-02-28'})).toBe('2032-02-29');});
 it('confirms exactly one installment and advances it atomically',()=>{let s=base();s=daily.saveRecurring(s,rule(s));const r=s.assistance!.recurring[0],n=daily.confirmRecurring(s,r.id,'2028-01-31');expect(n.transactions).toHaveLength(1);expect(n.payments[0].status).toBe('paid');expect(accountBalance(n,s.accounts[0].id)).toBe(90000);expect(n.assistance!.recurring[0].nextDate).toBe('2028-02-29');expect(()=>daily.confirmRecurring(n,r.id,'2028-01-31')).toThrow();expect(s.transactions).toHaveLength(0);});
 it('subtracts unreserved payments once and excludes already reserved ones',()=>{let s=base(),id=s.accounts[0].id;s=addGoal(s,{name:'Ціль',target:20000,dueDate:''});s=allocateGoal(s,s.goals[0].id,id,10000);for(const [amount,reserved,date] of [[20000,true,'2028-01-02'],[15000,false,'2028-01-03'],[8000,false,'2028-02-01']] as const)s=addPayment(s,{name:'Платіж',amount,accountId:id,category:'expense-0',date,status:'planned',reserved});s=daily.setNextIncome(s,'2028-01-11','2028-01-01');const f=daily.paydayForecast(s,'2028-01-01');expect(f.available).toBe(70000);expect(f.planned).toBe(15000);expect(f.remaining).toBe(55000);expect(f.days).toBe(10);expect(f.daily).toBe(5500);});
 it('accounts for overdue payable debt but never promises receivable debt as available money',()=>{let s=base();s=addDebt(s,{person:'A',direction:'payable',principal:20000,date:'2027-12-01',dueDate:'2027-12-31',note:''},'',false);s=addDebt(s,{person:'B',direction:'receivable',principal:90000,date:'2027-12-01',dueDate:'2028-01-03',note:''},'',false);s=daily.setNextIncome(s,'2028-01-11','2028-01-01');expect(daily.paydayForecast(s,'2028-01-01').remaining).toBe(80000);});
 it('does not count a linked reserved debt payment twice',()=>{let s=base();s=addDebt(s,{person:'A',direction:'payable',principal:20000,date:'2027-12-01',dueDate:'2028-01-04',note:''},'',false);s=addPayment(s,{name:'Борг',amount:10000,accountId:s.accounts[0].id,category:'Борг',date:'2028-01-03',status:'planned',reserved:true,debtId:s.debts[0].id});s=daily.setNextIncome(s,'2028-01-11','2028-01-01');expect(daily.paydayForecast(s,'2028-01-01').remaining).toBe(80000);});
 it('rejects malformed tools during backup restoration',()=>{const s=base();expect(()=>restoreFinanceState({...s,assistance:{templates:[{id:'x',name:'x',kind:'expense',accountId:'missing',category:'expense-0',amount:0,note:''}],recurring:[],nextIncomeDate:''}})).toThrow();});
 it('projects very old weekly bills without looping through each occurrence',()=>{let s=base();s=daily.saveRecurring(s,{...rule(s),frequency:'weekly',startDate:'1800-01-01',nextDate:'1800-01-01',amount:100});s=daily.setNextIncome(s,'2028-01-11','2028-01-01');const f=daily.paydayForecast(s,'2028-01-01');expect(f.configured).toBe(true);expect(f.recurring).toBeGreaterThan(1100000);expect(Number.isSafeInteger(f.remaining)).toBe(true);});
 it('reports enormous projections without crashing Home or rounding unsafe money',()=>{let s=base();s=daily.saveRecurring(s,{...rule(s),frequency:'weekly',startDate:'0001-01-01',nextDate:'0001-01-01',amount:100000000000});s=daily.setNextIncome(s,'2028-01-11','2028-01-01');expect(daily.paydayForecast(s,'2028-01-01')).toMatchObject({configured:false,error:expect.any(String)});expect(daily.paydayForecast(s,'2028-01-01').error).not.toBe('');});
 it('snoozes debt reminders without moving its due date',()=>{let s=base();s=addDebt(s,{person:'Друг',direction:'payable',principal:2000,date:'2028-01-01',dueDate:'2028-01-05',note:''},'',false);const d=s.debts[0];s=daily.setDebtReminder(s,d.id,d.dueDate,'2028-01-10');expect(daily.reminders(s,'2028-01-06').some(r=>r.id===d.id)).toBe(false);expect(s.debts[0].dueDate).toBe('2028-01-05');expect(daily.reminders(s,'2028-01-10').some(r=>r.id===d.id)).toBe(true);s=repayDebt(s,d.id,s.accounts[0].id,2000,'2028-01-10');expect(debtRemaining(s,d.id)).toBe(0);expect(daily.reminders(s,'2028-01-10')).toHaveLength(0);});
 it('undo restores a complete snapshot and rejects another user or newer state',()=>{const s=base(),n=addPayment(s,{name:'Платіж',amount:10000,accountId:s.accounts[0].id,category:'expense-0',date:'2028-01-02',status:'planned',reserved:true});const entry=undo.captureUndo(s,n,'user-a');expect(undo.undoState(n,entry,'user-a')).toEqual(s);expect(()=>undo.undoState(n,entry,'user-b')).toThrow();expect(()=>undo.undoState({...n,payments:[]},entry,'user-a')).toThrow();});
});
