import { describe, expect, it } from 'vitest';
import { parseMoney, createEmptyState, addAccount, addTransaction, accountBalance, totals, addGoal, allocateGoal, releaseGoal, addDebt, repayDebt, debtRemaining, removeTransaction, addPayment, payPayment, restoreFinanceState, cancelPayment, archiveAccount, updateTransaction, reactivateAccount } from './finance';
const setup = () => addAccount(createEmptyState(), {name:'Основна',type:'card',initialBalance:1000000,lastFour:'1234',color:'navy'});
describe('integer money', () => {
 it('parses Ukrainian decimals without float rounding',()=>expect(parseMoney('1 234,56')).toBe(123456));
 it('rejects precision beyond kopecks and negative money',()=>{expect(()=>parseMoney('10.001')).toThrow();expect(()=>parseMoney('-10')).toThrow();});
});
describe('backup restore',()=>{
 it('rejects unknown account references',()=>{const s=setup();s.transactions.push({id:'x',kind:'expense',amount:100,accountId:'missing',category:'Продукти',note:'',date:'2026-10-05'});expect(()=>restoreFinanceState(s)).toThrow();});
 it('rejects duplicate ids and invalid reserve amount',()=>{const s=setup();s.accounts.push({...s.accounts[0]});expect(()=>restoreFinanceState(s)).toThrow();const n=setup();n.goals.push({id:'g',name:'x',target:10000000,dueDate:'',allocations:[{accountId:n.accounts[0].id,amount:2000000}]});expect(()=>restoreFinanceState(n)).toThrow();});
 it('accepts an empty valid backup',()=>expect(restoreFinanceState(createEmptyState())).toEqual(createEmptyState()));
});
describe('finance behavior',()=>{
 it('edits an operation atomically while preserving its id',()=>{let s=setup();s=addTransaction(s,{kind:'expense',amount:100000,accountId:s.accounts[0].id,category:'Продукти',note:'',date:'2026-10-05'});const tx=s.transactions[0];const n=updateTransaction(s,tx.id,{...tx,amount:200000});expect(n.transactions[0].id).toBe(tx.id);expect(accountBalance(n,s.accounts[0].id)).toBe(800000);expect(()=>updateTransaction(s,tx.id,{...tx,amount:2000000})).toThrow();expect(accountBalance(s,s.accounts[0].id)).toBe(900000);});
 it('does not allow ordinary editing to detach a paid planned payment',()=>{let s=setup();s=addPayment(s,{name:'Оренда',amount:200000,accountId:s.accounts[0].id,category:'Житло',date:'2026-10-10',status:'planned',reserved:true});s=payPayment(s,s.payments[0].id);expect(()=>updateTransaction(s,s.transactions[0].id,{...s.transactions[0],amount:100000})).toThrow();});
 it('reactivates an archived account before reversing a transfer',()=>{let s=addAccount(setup(),{name:'Резерв',type:'card',initialBalance:0,lastFour:'',color:'steel'});const a=s.accounts[0].id;s=addTransaction(s,{kind:'transfer',amount:1000000,accountId:a,toAccountId:s.accounts[1].id,category:'',note:'',date:'2026-10-05'});s=reactivateAccount(archiveAccount(s,a),a);s=removeTransaction(s,s.transactions[0].id);expect(accountBalance(s,a)).toBe(1000000);expect(s.accounts[0].archived).toBe(false);});
 it('blocks archiving an account with an unreserved planned payment',()=>{let s=addAccount(createEmptyState(),{name:'Основна',type:'card',initialBalance:0,lastFour:'',color:'navy'});s=addPayment(s,{name:'Підписка',amount:10000,accountId:s.accounts[0].id,category:'Підписки',date:'2026-10-10',status:'planned',reserved:false});expect(()=>archiveAccount(s,s.accounts[0].id)).toThrow(/плат/);});
 it('cancels a planned payment and releases its reservation',()=>{let s=setup();s=addPayment(s,{name:'Оренда',amount:200000,accountId:s.accounts[0].id,category:'Житло',date:'2026-10-10',status:'planned',reserved:true});s=cancelPayment(s,s.payments[0].id);expect(totals(s,'2026-10').available).toBe(1000000);expect(s.payments).toHaveLength(0);});
 it('rejects reversal that restores money into an archived account',()=>{let s=addAccount(setup(),{name:'Резерв',type:'card',initialBalance:0,lastFour:'',color:'steel'});const a=s.accounts[0].id;s=addTransaction(s,{kind:'transfer',amount:1000000,accountId:a,toAccountId:s.accounts[1].id,category:'',note:'',date:'2026-10-05'});s=archiveAccount(s,a);expect(()=>removeTransaction(s,s.transactions[0].id)).toThrow(/архів/);});
 it('records expense and delete restores balance',()=>{let s=setup();const a=s.accounts[0].id;s=addTransaction(s,{kind:'expense',amount:10000,accountId:a,category:'Продукти',note:'',date:'2026-10-05'});expect(accountBalance(s,a)).toBe(990000);s=removeTransaction(s,s.transactions[0].id);expect(accountBalance(s,a)).toBe(1000000);});
 it('transfers preserve total and do not count as expense',()=>{let s=addAccount(setup(),{name:'Резерв',type:'card',initialBalance:0,lastFour:'',color:'steel'});s=addTransaction(s,{kind:'transfer',amount:100000,accountId:s.accounts[0].id,toAccountId:s.accounts[1].id,category:'',note:'',date:'2026-10-05'});expect(totals(s,'2026-10').balance).toBe(1000000);expect(totals(s,'2026-10').expense).toBe(0);expect(accountBalance(s,s.accounts[1].id)).toBe(100000);});
 it('reserves goal funds without changing balance and blocks double allocation',()=>{let s=addGoal(setup(),{name:'Резерв',target:2000000,dueDate:''});s=allocateGoal(s,s.goals[0].id,s.accounts[0].id,800000);expect(totals(s,'2026-10').balance).toBe(1000000);expect(totals(s,'2026-10').available).toBe(200000);expect(()=>allocateGoal(s,s.goals[0].id,s.accounts[0].id,300000)).toThrow();});
 it('prevents spending saved funds until explicitly released',()=>{let s=addGoal(setup(),{name:'Резерв',target:1000000,dueDate:''});s=allocateGoal(s,s.goals[0].id,s.accounts[0].id,900000);const tx={kind:'expense' as const,amount:200000,accountId:s.accounts[0].id,category:'Продукти',note:'',date:'2026-10-05'};expect(()=>addTransaction(s,tx)).toThrow();s=releaseGoal(s,s.goals[0].id,s.accounts[0].id,100000);expect(accountBalance(addTransaction(s,tx),s.accounts[0].id)).toBe(800000);});
 it('records loan repayment without counting principal as income',()=>{let s=addDebt(setup(),{person:'Олег',direction:'receivable',principal:200000,date:'2026-10-05',dueDate:'',note:''},sAccount(setup()),false);s=repayDebt(s,s.debts[0].id,s.accounts[0].id,50000,'2026-10-06');expect(debtRemaining(s,s.debts[0].id)).toBe(150000);expect(totals(s,'2026-10').income).toBe(0);expect(totals(s,'2026-10').balance).toBe(1050000);});
 it('rejects repayment larger than remaining debt',()=>{let s=addDebt(setup(),{person:'Олег',direction:'payable',principal:10000,date:'2026-10-05',dueDate:'',note:''},'',false);expect(()=>repayDebt(s,s.debts[0].id,s.accounts[0].id,20000,'2026-10-05')).toThrow();});
 it('settles a reserved payment once without double reserving funds',()=>{let s=setup();s=addPayment(s,{name:'Оренда',amount:200000,accountId:s.accounts[0].id,category:'Житло',date:'2026-10-10',status:'planned',reserved:true});expect(totals(s,'2026-10').available).toBe(800000);s=payPayment(s,s.payments[0].id);expect(totals(s,'2026-10').available).toBe(800000);expect(totals(s,'2026-10').balance).toBe(800000);expect(()=>payPayment(s,s.payments[0].id)).toThrow();});
 it('cannot delete income if it would invalidate existing savings',()=>{let s=setup();s=addTransaction(s,{kind:'income',amount:500000,accountId:s.accounts[0].id,category:'Зарплата',date:'2026-10-05',note:''});s=addGoal(s,{name:'Резерв',target:2000000,dueDate:''});s=allocateGoal(s,s.goals[0].id,s.accounts[0].id,1400000);expect(()=>removeTransaction(s,s.transactions[0].id)).toThrow();});
});
function sAccount(s:ReturnType<typeof setup>){return s.accounts[0].id;}
