import {describe,it,expect} from 'vitest';
import {createEmptyState,addAccount,addTransaction,accountBalance,totals,reconcileAccount,allocateGoal,releaseGoal,addGoal,restoreFinanceState,updateTransaction,removeTransaction,expenseParts} from './finance';
const date='2026-10-08';
function fixture(){const s=addAccount(createEmptyState(),{name:'Cash',type:'cash',initialBalance:100000,lastFour:'',color:'navy'});return s;}
describe('opening balances and reconciliation',()=>{
 it('does not classify existing opening money as income',()=>{const s=fixture();expect(totals(s,'2026-10').balance).toBe(100000);expect(totals(s,'2026-10').income).toBe(0);expect(s.transactions).toHaveLength(0);});
 it('records increase and decrease with no income or expense',()=>{const s=fixture(),id=s.accounts[0].id;const n=reconcileAccount(s,id,115025,'Forgotten cash',date);expect(accountBalance(n,id)).toBe(115025);expect(n.transactions[0].kind).toBe('adjustment-increase');expect(n.transactions[0].amount).toBe(15025);const down=reconcileAccount(n,id,90000,'Correction',date);expect(accountBalance(down,id)).toBe(90000);expect(totals(down,'2026-10')).toMatchObject({income:0,expense:0});expect(s.transactions).toHaveLength(0);});
 it('does not create a zero difference transaction',()=>{const s=fixture();expect(reconcileAccount(s,s.accounts[0].id,100000,'Match',date).transactions).toHaveLength(0);});
 it('can reconcile an accumulated balance larger than the single purchase cap',()=>{let s=addAccount(createEmptyState(),{name:'Large',type:'cash',initialBalance:100000000000,lastFour:'',color:'navy'});const id=s.accounts[0].id;s=addTransaction(s,{kind:'income',accountId:id,amount:100000000000,category:s.categories.find(c=>c.kind==='income')!.id,note:'Income',date});const n=reconcileAccount(s,id,0,'Correct accumulated balance',date);expect(accountBalance(n,id)).toBe(0);expect(n.transactions[0].amount).toBe(200000000000);expect(totals(n,'2026-10').expense).toBe(0);});
 it('rejects below-reserve balances, invalid inputs and archived accounts atomically',()=>{let s=fixture();s=addGoal(s,{name:'Goal',target:100000,dueDate:''});s=allocateGoal(s,s.goals[0].id,s.accounts[0].id,80000,date);const before=structuredClone(s);for(const actual of [79999,-1,NaN,0.5,100000000001])expect(()=>reconcileAccount(s,s.accounts[0].id,actual,'Reason',date)).toThrow();expect(()=>reconcileAccount(s,s.accounts[0].id,100001,'',date)).toThrow();expect(()=>reconcileAccount(s,s.accounts[0].id,100001,'Reason','2026-02-30')).toThrow();expect(s).toEqual(before);const archived={...fixture(),accounts:fixture().accounts};archived.accounts[0].archived=true;expect(()=>reconcileAccount(archived,archived.accounts[0].id,100,'Reason',date)).toThrow();});
});
describe('one expense with category parts',()=>{
 it('spends the total once and preserves parts through edit and deletion',()=>{const s=fixture(),cats=s.categories.filter(c=>c.kind==='expense').slice(0,2);const input={kind:'expense' as const,accountId:s.accounts[0].id,amount:80000,category:cats[0].id,note:'Receipt',date,splits:[{category:cats[0].id,amount:50000},{category:cats[1].id,amount:30000}]};const n=addTransaction(s,input);expect(n.transactions).toHaveLength(1);expect(accountBalance(n,s.accounts[0].id)).toBe(20000);expect(expenseParts(n.transactions[0])).toEqual(input.splits);expect(totals(n,'2026-10').expense).toBe(80000);const edited=updateTransaction(n,n.transactions[0].id,{...input,amount:70000,splits:[{category:cats[0].id,amount:40000},{category:cats[1].id,amount:30000}]});expect(accountBalance(edited,s.accounts[0].id)).toBe(30000);expect(removeTransaction(edited,edited.transactions[0].id).transactions).toHaveLength(0);});
 it('rejects mismatched totals, duplicate/wrong categories and non-expense parts',()=>{const s=fixture(),cats=s.categories.filter(c=>c.kind==='expense'),inc=s.categories.find(c=>c.kind==='income')!;const base={kind:'expense' as const,accountId:s.accounts[0].id,amount:80000,category:cats[0].id,note:'Receipt',date};for(const splits of [[{category:cats[0].id,amount:50000},{category:cats[1].id,amount:29999}],[{category:cats[0].id,amount:50000},{category:cats[0].id,amount:30000}],[{category:cats[0].id,amount:50000},{category:inc.id,amount:30000}],[{category:cats[0].id,amount:80000}],[{category:cats[0].id,amount:80000},{category:cats[1].id,amount:0}]])expect(()=>addTransaction(s,{...base,splits})).toThrow();expect(()=>addTransaction(s,{...base,kind:'income',category:inc.id,splits:[{category:cats[0].id,amount:50000},{category:cats[1].id,amount:30000}]})).toThrow();});
 it('rejects malformed split backups and unsupported schema versions',()=>{const s=fixture(),cats=s.categories.filter(c=>c.kind==='expense');const n=addTransaction(s,{kind:'expense',accountId:s.accounts[0].id,amount:80000,category:cats[0].id,note:'Receipt',date,splits:[{category:cats[0].id,amount:50000},{category:cats[1].id,amount:30000}]});const bad=structuredClone(n);bad.transactions[0].splits![0].amount=1;expect(()=>restoreFinanceState(bad)).toThrow();expect(()=>restoreFinanceState({...s,formatVersion:3})).toThrow();});
});
describe('dated goal flow history',()=>{
 it('records allocation and release without pretending existing savings have dates',()=>{let s=fixture();s=addGoal(s,{name:'Goal',target:100000,dueDate:''});s=allocateGoal(s,s.goals[0].id,s.accounts[0].id,50000,'2026-09-30');s=releaseGoal(s,s.goals[0].id,s.accounts[0].id,10000,date);expect(s.goals[0].history).toMatchObject([{amount:50000,direction:'save',date:'2026-09-30'},{amount:10000,direction:'release',date}]);expect(accountBalance(s,s.accounts[0].id)).toBe(100000);expect(totals(s,'2026-10').available).toBe(60000);});
});
