import { useState } from 'react';
import { Bell, CalendarDays, Pause, Pencil, Play, Plus, Repeat2, Trash2, Zap } from 'lucide-react';
import { Amount, Editor, Modal, PageTitle, type ViewProps } from '../components/ui';
import { PaymentConfirmation, QuickEntry, ReminderList, shortDate } from '../components/DailyWidgets';
import { assistanceOf, paydayForecast, removeRecurring, removeTemplate, saveRecurring, saveTemplate, setNextIncome, toggleRecurring } from '../lib/daily';
import { categoryColor, categoryName, categoryOptions, parseMoney, today } from '../lib/finance';
import { addDays } from '../lib/dates';
import type { QuickTemplate, RecurringPayment } from '../lib/types';

const frequencyLabel={weekly:'Щотижня',monthly:'Щомісяця',yearly:'Щороку'};
export function Tools(props:ViewProps){
 const {state,mutate,hide,busy,navigate}=props,a=assistanceOf(state),f=paydayForecast(state);
 const [edit,setEdit]=useState<{kind:'template'|'recurring';id?:string}|null>(null),[income,setIncome]=useState(false),[pay,setPay]=useState(''),[remove,setRemove]=useState<{kind:'template'|'recurring';id:string}|null>(null);
 const active=state.accounts.some(x=>!x.archived);
 return <><PageTitle title="Для щодня" description="Менше рутини: швидкі записи, платежі та спокійний план до наступного доходу."/><div className="tools-grid">
  <section className="panel tools-panel"><div className="panel-heading"><h2><Zap size={19}/> Швидкі шаблони</h2><button className="button secondary" disabled={busy||!active} onClick={()=>setEdit({kind:'template'})}><Plus size={16}/> Шаблон</button></div><p className="muted tools-description">Збережи категорію й рахунок. Наступного разу введи суму та підтвердь запис.</p>{!active&&<button className="text-button" onClick={()=>navigate('accounts')}>Спочатку створи рахунок</button>}{a.templates.length?<div className="tool-item-list">{a.templates.map(t=><div className="tool-item" key={t.id}><span className="category-dot" style={{background:categoryColor(state,t.category)}}/><div className="tool-item-copy"><strong>{t.name}</strong><small>{categoryName(state,t.category)} · {state.accounts.find(x=>x.id===t.accountId)?.name}{state.accounts.find(x=>x.id===t.accountId)?.archived?' · в архіві':''}</small></div>{t.amount>0&&<Amount value={t.amount} hide={hide}/>}<div className="row-actions"><button className="icon-button" disabled={busy} aria-label={'Редагувати шаблон '+t.name} onClick={()=>setEdit({kind:'template',id:t.id})}><Pencil size={16}/></button><button className="icon-button delete" disabled={busy} aria-label={'Видалити шаблон '+t.name} onClick={()=>setRemove({kind:'template',id:t.id})}><Trash2 size={16}/></button></div></div>)}</div>:<p className="tools-empty">Наприклад, «Кава», «Продукти» або «Проїзд».</p>}</section>
  <section className="panel tools-panel payday-panel"><div className="panel-heading"><h2><CalendarDays size={19}/> До наступного доходу</h2><button className="button secondary" disabled={busy} onClick={()=>setIncome(true)}>{a.nextIncomeDate?'Змінити дату':'Обрати дату'}</button></div>{f.configured?<><p className="muted">До {shortDate(f.date)} · {f.days} дн.</p><span className="payday-main"><Amount value={f.daily} hide={hide}/><small> / день</small></span>{f.shortfall>0&&<p className="negative">На заплановане бракує <Amount value={f.shortfall} hide={hide}/></p>}<div className="forecast-breakdown">{[['Доступно після відкладень і резервів',f.available],['Платежі без резерву',f.planned],['Повторювані платежі',f.recurring],['Борги до повернення',f.debts],['Залишок до наступного доходу',f.remaining]].map(([label,amount])=><div key={label as string}><span>{label}</span><Amount value={amount as number} hide={hide}/></div>)}</div><p className="tools-description muted">Орієнтир за поточними записами. Очікувані надходження й гроші, які тобі винні, не включені. Зарезервовані платежі враховано один раз.</p></>:<p className="muted tools-description">{f.error|| (a.nextIncomeDate?'Вказана дата вже минула. Обери наступну, щоб оновити розрахунок.':'Обери дату зарплати чи іншого наступного доходу. Сайт покаже, скільки залишається після твоїх планів.')}</p>}</section>
  <section className="panel tools-panel recurring-panel"><div className="panel-heading"><h2><Repeat2 size={19}/> Повторювані платежі</h2><button className="button secondary" disabled={busy||!active} onClick={()=>setEdit({kind:'recurring'})}><Plus size={16}/> Платіж</button></div><p className="muted tools-description">Оренда, інтернет і підписки. Гроші в обліку списуються після підтвердження. Для кількох пропущених періодів підтверджуй кожен окремо.</p>{a.recurring.length?<div className="tool-item-list">{a.recurring.map(r=><article className="recurring-item" key={r.id}><div className="tool-item"><span className="category-dot" style={{background:categoryColor(state,r.category)}}/><div className="tool-item-copy"><strong>{r.name}</strong><small>{frequencyLabel[r.frequency]} · {shortDate(r.nextDate)} · {state.accounts.find(x=>x.id===r.accountId)?.name}</small></div><Amount value={r.amount} hide={hide}/></div><div className="recurring-actions"><span className={'badge '+(!r.paused&&r.nextDate<today()?'overdue':'')}>{r.paused?'На паузі':r.nextDate<=today()?'Очікує оплати':'Заплановано'}</span><button className="text-button" disabled={busy} onClick={()=>mutate(s=>toggleRecurring(s,r.id),r.paused?'Платіж відновлено':'Платіж на паузі')}>{r.paused?<Play size={15}/>:<Pause size={15}/>} {r.paused?'Відновити':'Пауза'}</button><button className="icon-button" aria-label={'Редагувати платіж '+r.name} disabled={busy} onClick={()=>setEdit({kind:'recurring',id:r.id})}><Pencil size={16}/></button><button className="icon-button delete" aria-label={'Видалити повторюваний платіж '+r.name} disabled={busy} onClick={()=>setRemove({kind:'recurring',id:r.id})}><Trash2 size={16}/></button><button className="button secondary" disabled={busy||r.paused||r.nextDate>today()||!state.accounts.some(x=>x.id===r.accountId&&!x.archived)} onClick={()=>setPay(r.id)}>Записати оплату</button></div></article>)}</div>:<p className="tools-empty">Додай перший платіж, щоб більше не тримати його дату в голові.</p>}</section>
  <section className="panel tools-panel reminders-panel"><div className="panel-heading"><h2><Bell size={19}/> Найближчі нагадування</h2></div><p className="muted tools-description">Платежі й повернення боргів на найближчі три дні та прострочені записи. Нагадування видно в сайті, коли ти його відкриваєш.</p><ReminderList {...props}/></section>
 </div><QuickEntry {...props}/>{edit&&<ToolForm {...props} kind={edit.kind} id={edit.id} onClose={()=>setEdit(null)}/>} {income&&<Editor open title="Дата наступного доходу" onClose={()=>setIncome(false)} description="Обери майбутню дату в межах року. Залиш поле порожнім, щоб вимкнути розрахунок." fields={[{name:'date',label:'Наступний дохід',type:'date',value:a.nextIncomeDate,min:addDays(today(),1),max:addDays(today(),365),required:false}]} onSubmit={v=>mutate(s=>setNextIncome(s,v.date),'Дату доходу збережено')}/>} {pay&&<PaymentConfirmation {...{state,mutate,hide}} kind="recurring" id={pay} onClose={()=>setPay('')}/>} {remove&&<Modal open onClose={()=>setRemove(null)} title="Прибрати з інструментів?"><p className="form-description">{remove.kind==='template'?'Шаблон':'Повторюваний платіж'} буде видалено. Уже записані операції залишаться в журналі.</p><div className="form-footer"><button className="button secondary" onClick={()=>setRemove(null)}>Залишити</button><button className="button danger" disabled={busy} onClick={async()=>{if(await mutate(s=>remove.kind==='template'?removeTemplate(s,remove.id):removeRecurring(s,remove.id),'Інструмент видалено'))setRemove(null);}}>Видалити</button></div></Modal>}</>;
}
function ToolForm({state,mutate,kind,id,onClose}:ViewProps&{kind:'template'|'recurring';id?:string;onClose:()=>void}){
 const a=assistanceOf(state),old=kind==='template'?a.templates.find(t=>t.id===id):a.recurring.find(r=>r.id===id),template=old as QuickTemplate|undefined,rule=old as RecurringPayment|undefined;
 const [name,setName]=useState(old?.name||''),[type,setType]=useState<'expense'|'income'>(kind==='template'&&template?.kind||'expense'),[accountId,setAccountId]=useState(old?.accountId||state.accounts.find(x=>!x.archived)?.id||''),[category,setCategory]=useState(old?.category||categoryOptions(state,type)[0]?.value||''),[amount,setAmount]=useState(old?.amount?String(old.amount/100):''),[note,setNote]=useState(kind==='template'?template?.note||'':''),[frequency,setFrequency]=useState<RecurringPayment['frequency']>(rule?.frequency||'monthly'),[date,setDate]=useState(kind==='recurring'?rule?.nextDate||today():today()),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const accounts=state.accounts.filter(x=>!x.archived),categories=categoryOptions(state,type);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setSaving(true);try{const value=amount?parseMoney(amount,kind==='template'):kind==='template'?0:parseMoney('');const result=await mutate(s=>kind==='template'?saveTemplate(s,{name,kind:type,accountId,category,amount:value,note:note||name},id):saveRecurring(s,{name,accountId,category,amount:value,frequency,startDate:rule&&rule.frequency===frequency&&rule.nextDate===date?rule.startDate:date,nextDate:date,paused:rule?.paused||false},id),kind==='template'?'Шаблон збережено':'Повторюваний платіж збережено');if(result)onClose();}catch(e){setError(e instanceof Error?e.message:'Не вдалося зберегти.');}finally{setSaving(false);}}
 return <Modal open onClose={()=>{if(!saving)onClose();}} title={kind==='template'?(id?'Редагувати шаблон':'Новий шаблон'):(id?'Редагувати повторюваний платіж':'Новий повторюваний платіж')}><form onSubmit={submit}><fieldset className="editor-fieldset form-fields" disabled={saving}><label>Назва<input required maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder={kind==='template'?'Наприклад, Кава':'Наприклад, Інтернет'}/></label>{kind==='template'&&<label>Тип запису<select value={type} onChange={e=>{const next=e.target.value as 'expense'|'income';setType(next);setCategory(categoryOptions(state,next)[0]?.value||'');}}><option value="expense">Витрата</option><option value="income">Надходження</option></select></label>}<label>Рахунок<select required value={accountId} onChange={e=>setAccountId(e.target.value)}><option disabled value="">Обери рахунок</option>{accounts.map(x=><option key={x.id} value={x.id}>{x.name} · {x.type==='cash'?'готівка':x.type==='card'?'картка':'заощадження'}</option>)}</select></label><label>Категорія<select required value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label>{kind==='template'?'Сума за замовчуванням, ₴':'Сума платежу, ₴'}<input inputMode="decimal" value={amount} required={kind==='recurring'} onChange={e=>setAmount(e.target.value)} maxLength={30} placeholder={kind==='template'?'Необов’язково':'0,00'}/>{kind==='template'&&<small>Залиш порожнім, щоб вводити суму щоразу.</small>}</label>{kind==='template'?<label>Примітка<input maxLength={200} value={note} onChange={e=>setNote(e.target.value)} placeholder="За замовчуванням — назва шаблону"/></label>:<><label>Повторювати<select value={frequency} onChange={e=>setFrequency(e.target.value as RecurringPayment['frequency'])}>{Object.entries(frequencyLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Найближча дата платежу<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/><small>Дата списання в журналі — день підтвердження оплати.</small></label></>}</fieldset>{error&&<div className="form-error" role="alert">{error}</div>}<div className="form-footer"><button type="button" className="button secondary" disabled={saving} onClick={onClose}>Скасувати</button><button className="button primary" disabled={saving||!accounts.length}>{saving?'Зберігаю…':'Зберегти'}</button></div></form></Modal>;
}
