import { useState } from 'react';
import { Bell, ChevronRight, Clock3, Plus, Zap } from 'lucide-react';
import { Amount, Editor, Modal, type ViewProps } from './ui';
import { TransactionEditor } from './TransactionEditor';
import { assistanceOf, reminders, paydayForecast, templateTransaction, confirmRecurring, setDebtReminder, addDays } from '../lib/daily';
import { categoryColor, categoryName, payPayment, today } from '../lib/finance';
import type { FinanceState } from '../lib/types';

export const shortDate=(date:string)=>new Date(date+'T12:00:00').toLocaleDateString('uk-UA',{day:'numeric',month:'short',year:'numeric'});
export function QuickEntry(props:ViewProps){
 const {state,hide,busy,navigate}=props,[selected,setSelected]=useState('');const templates=assistanceOf(state).templates;
 const template=templates.find(t=>t.id===selected),active=template&&state.accounts.some(a=>a.id===template.accountId&&!a.archived);
 return <section className="quick-entry" aria-label="Швидкі записи"><div className="flex-between"><h2><Zap size={16}/> Записати швидко</h2><button className="text-button" onClick={()=>navigate('tools')}>{templates.length?'Мої шаблони':'Створити шаблон'}<ChevronRight size={15}/></button></div>{templates.length?<div className="quick-template-list">{templates.map(t=>{const account=state.accounts.find(a=>a.id===t.accountId);return <button key={t.id} className="quick-template" disabled={busy||!account||account.archived} title={categoryName(state,t.category)+' · '+account?.name} onClick={()=>setSelected(t.id)}><span className="category-dot" style={{background:categoryColor(state,t.category)}}/><span>{t.name}</span>{t.amount>0&&<Amount value={t.amount} hide={hide}/>}</button>;})}</div>:<p className="muted">Кава, продукти чи проїзд — збережи рахунок і категорію, щоб вводити лише суму.</p>}{active&&<TransactionEditor open onClose={()=>setSelected('')} state={state} mutate={props.mutate} hide={hide} initialKind={template.kind} initialAccountId={template.accountId} initialValues={templateTransaction(state,template.id)}/>}</section>;
}
export function PaymentConfirmation({state,mutate,hide,onClose,kind,id}:{state:FinanceState;mutate:ViewProps['mutate'];hide:boolean;onClose:()=>void;kind:'payment'|'recurring';id:string}){
 const [saving,setSaving]=useState(false);const item=kind==='recurring'?assistanceOf(state).recurring.find(r=>r.id===id):state.payments.find(p=>p.id===id);if(!item)return null;
 const account=state.accounts.find(a=>a.id===item.accountId),date=kind==='recurring'?'nextDate' in item?item.nextDate:'':'date' in item?item.date:'';
 return <Modal open onClose={()=>{if(!saving)onClose();}} title="Підтвердити оплату"><p className="form-description">Записати оплату «{item.name}» з рахунку «{account?.name}»? Це змінить баланс у твоєму обліку.</p><div className="payment-confirm-amount"><Amount value={item.amount} hide={hide}/></div><p className="muted">Платіж за {shortDate(date)}{kind==='recurring'?' · після оплати з’явиться наступна дата':''}</p><div className="form-footer"><button className="button secondary" disabled={saving} onClick={onClose}>Скасувати</button><button className="button primary" disabled={saving} onClick={async()=>{setSaving(true);try{if(await mutate(s=>kind==='recurring'?confirmRecurring(s,id):payPayment(s,id),'Оплату записано'))onClose();}finally{setSaving(false);}}}>{saving?'Зберігаю…':'Підтвердити оплату'}</button></div></Modal>;
}
export function ReminderList({state,mutate,hide,busy,navigate}:ViewProps){
 const [pay,setPay]=useState<{kind:'payment'|'recurring';id:string}|null>(null),[snooze,setSnooze]=useState('');const list=reminders(state),debt=state.debts.find(d=>d.id===snooze);
 return <>{list.length?<div className="reminder-list">{list.map(r=><article className="reminder-row" key={r.kind+r.id}><span className={'reminder-icon '+(r.date<today()?'negative':'')}><Bell size={18}/></span><div className="reminder-copy"><strong>{r.title}</strong><small>{r.kind==='debt'?(r.direction==='payable'?'Тобі повернути':'Мають повернути тобі'):r.kind==='recurring'?'Повторюваний платіж':'Запланований платіж'} · {shortDate(r.date)}</small></div><Amount value={r.amount} hide={hide}/><div className="reminder-actions">{r.kind==='debt'?<><button className="text-button" disabled={busy} onClick={()=>setSnooze(r.id)}><Clock3 size={14}/> Відкласти</button><button className="text-button" onClick={()=>navigate('debts')}>До боргу<ChevronRight size={14}/></button></>:<button className="button secondary" disabled={busy||r.kind==='recurring'&&r.date>today()} onClick={()=>setPay({kind:r.kind as 'payment'|'recurring',id:r.id})}>{r.kind==='recurring'&&r.date>today()?'Ще не настав':'Записати оплату'}</button>}</div></article>)}</div>:<p className="muted">На найближчі три дні нагадувань немає.</p>}{pay&&<PaymentConfirmation {...{state,mutate,hide}} {...pay} onClose={()=>setPay(null)}/>} {debt&&<Editor open onClose={()=>setSnooze('')} title={'Нагадати: '+debt.person} description="Строк повернення боргу залишиться тим самим. До вибраної дати нагадування буде приховано." fields={[{name:'date',label:'Нагадати знову',type:'date',min:addDays(today(),1),value:addDays(today(),1)}]} onSubmit={v=>mutate(s=>setDebtReminder(s,debt.id,debt.dueDate,v.date),'Нагадування відкладено')}/>}</>;
}
export function DailySummary(props:ViewProps){const f=paydayForecast(props.state),count=reminders(props.state).length;return <div className="daily-summary"><QuickEntry {...props}/>{f.configured&&<button className="payday-brief" onClick={()=>props.navigate('tools')}><span>{f.shortfall?'До наступного доходу бракує':'Орієнтир до наступного доходу'}</span><strong><Amount value={f.shortfall||f.daily} hide={props.hide}/>{!f.shortfall&&<small> / день</small>}</strong><ChevronRight size={17}/></button>}{count>0&&<details className="home-reminders"><summary><Bell size={16}/> Найближчі нагадування <span>{count}</span></summary><ReminderList {...props}/></details>}</div>;}
