import {Plus,Trash2} from 'lucide-react';
import type {FinanceState} from '../lib/types';
import {categoryOptions,categoryColor,parseMoney} from '../lib/finance';
import {Amount} from './ui';
import '../ledger-tools.css';
export interface SplitField {category:string;amount:string}
export function ExpenseSplitFields({state,parts,onChange,total,hide}:{state:FinanceState;parts:SplitField[];onChange:(parts:SplitField[])=>void;total:string;hide?:boolean}){
 const categories=categoryOptions(state,'expense');let difference:number|undefined;try{difference=parseMoney(total)-parts.reduce((v,p)=>v+parseMoney(p.amount,true),0);}catch{}
 const change=(i:number,patch:Partial<SplitField>)=>onChange(parts.map((p,index)=>index===i?{...p,...patch}:p));
 return <div className="split-editor"><p className="form-description">Одна покупка, кілька категорій. Сума частин має точно дорівнювати загальній сумі.</p>{parts.map((p,i)=><div className="split-row" key={i}><label><span className="category-label"><span className="category-dot" style={{background:categoryColor(state,p.category)}}/>Категорія {i+1}</span><select aria-label={'Категорія частини '+(i+1)} required value={p.category} onChange={e=>change(i,{category:e.target.value})}>{categories.map(c=><option key={c.value} value={c.value} disabled={parts.some((other,index)=>index!==i&&other.category===c.value)}>{c.label}</option>)}</select></label><label>Сума {i+1}, ₴<input aria-label={'Сума частини '+(i+1)} required type={hide?'password':'text'} inputMode="decimal" maxLength={30} placeholder="0,00" value={p.amount} onChange={e=>change(i,{amount:e.target.value})}/></label><button type="button" className="icon-button delete" aria-label={'Прибрати частину '+(i+1)} disabled={parts.length<=2} onClick={()=>onChange(parts.filter((_,index)=>index!==i))}><Trash2 size={16}/></button></div>)}<div className="split-balance"><span>{difference===undefined?'Заповни суми всіх частин':difference===0?'Суми збігаються':difference>0?'Ще розподілити':'Частини перевищують суму'} {difference!==undefined&&difference!==0&&<Amount value={Math.abs(difference)} hide={hide}/>}</span><button type="button" className="text-button" disabled={parts.length>=Math.min(20,categories.length)} onClick={()=>onChange([...parts,{category:categories.find(c=>!parts.some(p=>p.category===c.value))!.value,amount:''}])}><Plus size={14}/> Частина</button></div></div>;
}
