import {useState} from 'react';
import {Amount,Modal,type Mutate} from './ui';
import {accountBalance,accountReserved,parseMoney,reconcileAccount,today} from '../lib/finance';
import type {FinanceState} from '../lib/types';
import '../ledger-tools.css';
export function ReconcileAccount({state,mutate,hide,accountId,onClose}:{state:FinanceState;mutate:Mutate;hide:boolean;accountId:string;onClose:()=>void}){
 const a=state.accounts.find(a=>a.id===accountId),current=accountBalance(state,accountId),reserved=accountReserved(state,accountId);
 const [actual,setActual]=useState(''),[note,setNote]=useState(''),[date,setDate]=useState(today()),[saving,setSaving]=useState(false),[error,setError]=useState('');
 let value:number|undefined;try{if(actual.trim())value=parseMoney(actual,true);}catch{}
 const difference=value===undefined?undefined:value-current;
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setSaving(true);try{const value=parseMoney(actual,true);if(await mutate(s=>{if(accountBalance(s,accountId)!==current)throw new Error('Баланс змінився. Перевір різницю ще раз.');return reconcileAccount(s,accountId,value,note,date);},'Баланс звірено'))onClose();}catch(e){setError(e instanceof Error?e.message:'Не вдалося звірити баланс.');}finally{setSaving(false);}}
 return <Modal open onClose={()=>{if(!saving)onClose();}} title={'Звірити баланс: '+(a?.name||'рахунок')}><form onSubmit={submit}><p className="form-description">Вкажи фактичний залишок у банку або перераховану готівку. Різниця буде окремим коригуванням, без зміни доходів і витрат.</p><div className="reconcile-preview"><div><span>За обліком</span><Amount value={current} hide={hide}/></div><div><span>Відкладення й резерви</span><Amount value={reserved} hide={hide}/></div>{difference!==undefined&&<div><span>{difference===0?'Баланс збігається':difference>0?'Коригування в плюс':'Коригування в мінус'}</span><Amount value={Math.abs(difference)} hide={hide}/></div>}</div><fieldset className="editor-fieldset form-fields" disabled={saving}><label>Фактичний баланс, ₴<input required type={hide?'password':'text'} inputMode="decimal" maxLength={30} placeholder="0,00" value={actual} onChange={e=>setActual(e.target.value)}/></label><label>Дата звірки<input required type="date" max={today()} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Пояснення<input required maxLength={200} placeholder="Наприклад, пропущений запис" value={note} onChange={e=>setNote(e.target.value)}/></label></fieldset>{value!==undefined&&value<reserved&&<p className="form-error">Спочатку вивільни відкладення або резерви до фактичного залишку.</p>}{error&&<div className="form-error" role="alert">{error}</div>}<div className="form-footer"><button type="button" className="button secondary" disabled={saving} onClick={onClose}>Закрити</button><button className="button primary" disabled={saving||difference===undefined||difference===0||value!<reserved}>{saving?'Зберігаю…':'Підтвердити коригування'}</button></div></form></Modal>;
}
