import { useEffect, useRef, useState, type ReactNode } from 'react';
import { motion } from 'motion/react';
import { X, Plus, ChevronRight, Wallet, Coffee, ShoppingBag, ArrowDownLeft, ArrowUpRight, ArrowLeftRight, ShieldCheck, Check } from 'lucide-react';
import type { FinanceState, Transaction } from '../lib/types';
import { money, categoryName, categoryColor } from '../lib/finance';
export type Mutate = (transform:(s:FinanceState)=>FinanceState, message?:string)=>Promise<boolean>;
export interface ViewProps {state:FinanceState;mutate:Mutate;hide:boolean;busy:boolean;navigate:(page:string)=>void}
export const Amount=({value,hide,className=''}:{value:number;hide?:boolean;className?:string})=><span className={className}>{hide?'••••• ₴':money(value)}</span>;
export function Empty({title,description,action}:{title:string;description:string;action?:ReactNode}){return <div className="empty"><div className="empty-icon"><Wallet/></div><h3>{title}</h3><p>{description}</p>{action}</div>;}
export function PageTitle({title,description,action}:{title:string;description:string;action?:ReactNode}){return <div className="page-title"><div><h1>{title}</h1><p>{description}</p></div>{action}</div>;}
export function AddButton({onClick,children='Додати'}:{onClick:()=>void;children?:ReactNode}){return <button className="button primary" onClick={onClick}><Plus size={18}/>{children}</button>;}
export function Progress({value,color}:{value:number;color?:string}){return <div className="progress" role="progressbar" aria-valuenow={Math.round(Math.min(100,Math.max(0,value)))} aria-valuemin={0} aria-valuemax={100}><motion.div initial={false} animate={{scaleX:Math.min(100,Math.max(0,value))/100}} transition={{duration:.35,ease:'easeOut'}} style={{transformOrigin:'left',background:color}}/></div>;}
export function TransactionIcon({tx,state}:{tx:Transaction;state:FinanceState}){const Icon=tx.kind==='transfer'?ArrowLeftRight:tx.kind==='income'?ArrowDownLeft:categoryName(state,tx.category)==='Кафе та доставка'?Coffee:tx.kind==='expense'?ShoppingBag:ArrowUpRight;return <span className={'transaction-icon '+(tx.kind==='income'?'positive':tx.kind==='transfer'?'blue':'')} style={['income','expense'].includes(tx.kind)?{color:categoryColor(state,tx.category),background:categoryColor(state,tx.category)+'1a'}:undefined}><Icon size={21}/></span>;}
export const KIND_LABEL:Record<string,string>={income:'Надходження',expense:'Витрата',transfer:'Переказ',borrow:'Отримана позика',lend:'Позичені гроші','repay-payable':'Повернення боргу','repay-receivable':'Повернули борг'};
export function TransactionRow({tx,state,hide,action}:{tx:Transaction;state:FinanceState;hide:boolean;action?:ReactNode}){const positive=['income','borrow','repay-receivable'].includes(tx.kind);return <div className="transaction-row"><TransactionIcon tx={tx} state={state}/><div className="transaction-text"><strong>{tx.note||categoryName(state,tx.category)||KIND_LABEL[tx.kind]}</strong><small>{state.accounts.find(a=>a.id===tx.accountId)?.name} {['income','expense'].includes(tx.kind)?'· '+categoryName(state,tx.category):''} {tx.kind==='transfer'?'→ '+state.accounts.find(a=>a.id===tx.toAccountId)?.name:''} · {new Date(tx.date+'T12:00:00').toLocaleDateString('uk-UA',{day:'numeric',month:'short'})}</small></div><div className={'transaction-amount '+(positive?'positive':tx.kind==='transfer'?'':'negative')}>{hide?'•••••':(positive?'+':tx.kind==='transfer'?'':'−')+money(tx.amount)}<small>{KIND_LABEL[tx.kind]}</small></div>{action}</div>;}
export function Modal({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}){const [saveError,setSaveError]=useState('');useEffect(()=>{if(!open){setSaveError('');return;}const fail=(e:Event)=>setSaveError((e as CustomEvent<string>).detail),start=()=>setSaveError('');window.addEventListener('finance-save-error',fail);window.addEventListener('finance-save-start',start);return()=>{window.removeEventListener('finance-save-error',fail);window.removeEventListener('finance-save-start',start);};},[open]);const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;if(open&&!d?.open)d?.showModal();if(!open&&d?.open)d.close();},[open]);return <dialog ref={ref} className="modal" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-content"><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="Закрити" onClick={onClose}><X/></button></div>{children}{saveError&&<div className="form-error" role="alert">{saveError}</div>}</div></dialog>;}
export interface Field {name:string;label:string;type?:string;value?:string;options?:{value:string;label:string}[];required?:boolean;hint?:string;min?:string;max?:string;placeholder?:string}
export function Editor({open,onClose,title,fields,onSubmit,submitLabel='Зберегти',description,beforeFields}:{open:boolean;onClose:()=>void;title:string;fields:Field[];onSubmit:(values:Record<string,string>)=>Promise<boolean>|boolean;submitLabel?:string;description?:string;beforeFields?:ReactNode}){const formRef=useRef<HTMLFormElement>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false);useEffect(()=>{if(open){setError('');formRef.current?.reset();}},[open]);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');setSaving(true);const v=Object.fromEntries(new FormData(e.currentTarget).entries()) as Record<string,string>;try{if(await onSubmit(v))onClose();}catch(e){setError(e instanceof Error?e.message:'Не вдалося зберегти.');}finally{setSaving(false);}}return <Modal open={open} onClose={()=>{if(!saving)onClose();}} title={title}><form ref={formRef} onSubmit={submit}>{beforeFields}{description&&<p className="form-description">{description}</p>}<fieldset className="editor-fieldset form-fields" disabled={saving}>{fields.map(f=><label key={f.name}>{f.label}{f.options?<select name={f.name} defaultValue={f.value} required={f.required??true}>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='checkbox'?<input className="checkbox" type="checkbox" name={f.name} defaultChecked={f.value==='true'}/>:<input name={f.name} type={f.type||'text'} defaultValue={f.value} required={f.required??true} min={f.min} max={f.max} maxLength={f.type==='date'?undefined:200} placeholder={f.placeholder} inputMode={f.name==='amount'||f.name==='target'||f.name==='initialBalance'?'decimal':undefined}/>} {f.hint&&<small>{f.hint}</small>}</label>)}</fieldset>{error&&<div className="form-error" role="alert">{error}</div>}<div className="form-footer"><button type="button" className="button secondary" onClick={onClose} disabled={saving}>Скасувати</button><button className="button primary" disabled={saving}>{saving?'Зберігаю…':submitLabel}<Check size={16}/></button></div></form></Modal>;}
export const LinkButton=({children,onClick}:{children:ReactNode;onClick:()=>void})=><button className="text-button" onClick={onClick}>{children}<ChevronRight size={16}/></button>;
export const Shield=()=> <div className="shield"><ShieldCheck size={62} strokeWidth={1.3}/></div>;
